/**
 * An in-memory PostgreSQL (PGlite) with the app's real schema, for `db-*` suites.
 *
 * The DDL is generated from lib/db/schema.ts by drizzle-kit, so a column added to the schema
 * exists here with no second file to keep in step. Nothing here reads DATABASE_URL, and no
 * test can reach a real database.
 */
import { PGlite } from '@electric-sql/pglite';
import { drizzle } from 'drizzle-orm/pglite';
import { existsSync, readFileSync } from 'node:fs';
import { createRequire } from 'node:module';
import { setTestDb } from './lib-db-stub.mjs';
import * as main from '../../lib/db/schema';
import * as radar from '../../lib/db/schema-radar';
import * as compliance from '../../lib/db/schema-compliance';
import * as ai from '../../lib/db/schema-ai';
import * as ops from '../../lib/db/schema-ops';

// schema.ts re-exports the four modules below, but they import `users` back from it: loaded
// through the cycle, the radar tables are missing from its namespace. Merging the parts
// explicitly gives drizzle-kit the whole schema whatever the load order was.
const schema = { ...main, ...radar, ...compliance, ...ai, ...ops };

// Belt and braces: nothing in a db-* suite may reach a real mailbox or database, whatever the
// shell it runs from has exported.
for (const k of ['SMTP_USER', 'SMTP_PASS', 'DATABASE_URL', 'SERPAPI_API_KEY']) delete process.env[k];

// And no network: a db-* suite that needs a response stubs fetch itself; one that forgets
// fails loudly here instead of quietly making a live (possibly paid) call.
globalThis.fetch = (async (input: unknown) => {
  throw new Error(`tests/db: network is disabled in db-* suites (fetch ${String(input)})`);
}) as typeof fetch;

const req = createRequire(import.meta.url);
req('./render-redirect.cjs');

type KitApi = {
  generateDrizzleJson: (s: Record<string, unknown>) => unknown;
  generateMigration: (a: unknown, b: unknown) => Promise<string[]>;
};

/** The CREATE statements for the whole schema, generated by drizzle-kit (about 5 seconds). */
export async function buildDdl(): Promise<string[]> {
  const kit = req('drizzle-kit/api') as KitApi;
  return kit.generateMigration(
    kit.generateDrizzleJson({}),
    kit.generateDrizzleJson(schema as unknown as Record<string, unknown>),
  );
}

/**
 * `npm test` generates the DDL once and shares it with every db-* suite through
 * TEST_DB_DDL_FILE; a suite run by hand finds no file and generates its own.
 */
async function ddl(): Promise<string[]> {
  const file = process.env.TEST_DB_DDL_FILE;
  if (file && existsSync(file)) return JSON.parse(readFileSync(file, 'utf8')) as string[];
  return buildDdl();
}

export async function createTestDb() {
  const pg = new PGlite();
  for (const s of await ddl()) await pg.exec(s);
  const db = drizzle(pg, { schema });
  return { pg, db, close: () => pg.close() };
}

/** Creates the database AND installs it as `@/lib/db` for the modules under test. */
export async function installTestDb() {
  const t = await createTestDb();
  setTestDb(t.db);
  return t;
}

export { schema };
