/**
 * Known-bad-document integration tests — task 6.11, design.md §6.
 *
 * Every rule in REQ-6.1 exists because some parser mishandles the thing it forbids. The
 * only way to know the defences work is to build documents that break each rule, run
 * them through the real renderer and the real verifier, and check something actually
 * objects. A rule nobody has watched fire is a comment, not a check.
 *
 * Each case below names the layer that catches it, because they are not the same layer:
 *
 *   selfTest            reads the generated bytes back and fails on what did not survive
 *   scoreFormatting     inspects the document model and fails on what should never be in it
 *   coerceHeading       makes a bad heading physically unable to reach either renderer
 *
 * PDF coverage: `@react-pdf/renderer` publishes ESM-only export conditions that tsx
 * cannot resolve (the same limitation scripts/smoke.mts records), so the PDF renderer is
 * exercised in the Next runtime via GET /api/dev/selftest rather than here. The document
 * model, the heading allow-list and the date formatter tested here are shared by both
 * renderers, so what is PDF-specific is the layout code alone.
 */

import { assert, report, testAsync } from './harness.mjs';
import { renderResumeDocx } from '@/lib/render/docx';
import { selfTest } from '@/lib/render/selftest';
import { coerceHeading, isAllowedHeading } from '@/lib/render/headings';
import { containsNumericDate, formatDateRange } from '@/lib/render/dates';
import { scoreFormatting } from '@/lib/quality/formatting';
import type { ResumeDocument } from '@/lib/types';

/* ------------------------------------------------------------- fixtures ---- */

function goodDoc(): ResumeDocument {
  return {
    id: 'd1',
    userId: 'u1',
    contact: {
      fullName: 'Anand Sundaramoorthy',
      email: 'anand@example.com',
      phone: '+91 90000 00000',
      location: 'Chennai, India',
      portfolioUrl: 'anandsundaramoorthy.com',
      githubUrl: 'github.com/anand',
    },
    sections: [
      {
        key: 'skills',
        heading: 'Skills',
        items: [
          {
            text: 'PostgreSQL, React, TypeScript, Node.js, Docker, Terraform, GraphQL',
            sourceRecordId: null,
          },
        ],
      },
      {
        key: 'experience',
        heading: 'Experience',
        items: [],
        groups: [
          {
            title: 'Senior Engineer',
            subtitle: 'Acme',
            dateRange: 'Jan 2022 – Present',
            items: [
              {
                text: 'Optimized PostgreSQL queries serving 200K daily requests, cutting p95 latency 40 percent.',
                sourceRecordId: 'b1',
              },
              {
                text: 'Led the migration of the billing service to Terraform-managed infrastructure.',
                sourceRecordId: 'b2',
              },
            ],
          },
        ],
      },
      {
        key: 'education',
        heading: 'Education',
        items: [
          { text: 'B.E. Computer Science, Anna University', sourceRecordId: 'e1' },
        ],
      },
    ],
    jobRequirement: null,
    renderMode: 'ats-strict',
    recordHashSnapshot: ['h1', 'h2'],
    createdAt: new Date('2024-06-01'),
  };
}

const failures = (r: Awaited<ReturnType<typeof selfTest>>) =>
  r.issues.filter((i) => i.severity === 'fail').map((i) => i.check);

const rules = (d: ResumeDocument) =>
  [...new Set(scoreFormatting(d).violations.map((v) => v.rule))];

/* ---------------------------------------------------------------- suite ---- */

await (async () => {
  console.log('\nrendering a good document');

  await testAsync('a compliant document renders and passes the round-trip cleanly', async () => {
    const doc = goodDoc();
    const buffer = await renderResumeDocx(doc);
    const result = await selfTest(buffer, 'docx', doc);

    assert.deepEqual(
      result.issues,
      [],
      `a good document must raise nothing at all, got ${JSON.stringify(result.issues)}`,
    );
    assert.equal(result.passed, true);
    assert.ok(result.extractedChars > 200, `only ${result.extractedChars} chars extracted`);
    assert.deepEqual(scoreFormatting(doc).violations, []);
  });

  await testAsync('name, email, URLs and skills all survive being parsed back', async () => {
    const doc = goodDoc();
    const text = (await selfTest(await renderResumeDocx(doc), 'docx', doc)).extractedText
      .toLowerCase();

    for (const needle of [
      'anand sundaramoorthy',
      'anand@example.com',
      'anandsundaramoorthy.com',
      'github.com/anand',
      'postgresql',
      'experience',
    ]) {
      assert.ok(text.includes(needle), `"${needle}" did not survive the round-trip`);
    }
  });

  console.log('\nknown-bad documents (each must be caught)');

  // --- icon glyph -----------------------------------------------------------
  await testAsync('catches an icon-font glyph that reached the rendered file', async () => {
    const doc = goodDoc();
    // U+F0E0 — a private-use codepoint, which is where an icon font puts its envelope.
    // Written by codepoint rather than pasted: a glyph that shows as nothing in an
    // editor is exactly the kind of character that gets lost while being copied.
    const ICON = String.fromCodePoint(0xf0e0);
    doc.contact.email = `${ICON} anand@example.com`;
    doc.sections[0].items[0].text = `${ICON} PostgreSQL, React, TypeScript`;

    const result = await selfTest(await renderResumeDocx(doc), 'docx', doc);
    assert.equal(result.passed, false, 'a document carrying an icon glyph must not pass');
    assert.ok(
      failures(result).includes('no-garbled-glyphs'),
      `expected no-garbled-glyphs, got ${JSON.stringify(failures(result))}`,
    );
  });

  await testAsync('catches an emoji in the document model before it is rendered', async () => {
    const doc = goodDoc();
    doc.sections[1].groups![0].items[0].text = '📈 Optimized PostgreSQL queries.';
    assert.ok(rules(doc).includes('no-icon-glyphs'));
  });

  // --- numeric date ---------------------------------------------------------
  await testAsync('catches a locale-ambiguous numeric date', async () => {
    const doc = goodDoc();
    doc.sections[1].groups![0].dateRange = '01/2022 - 05/2024';

    assert.ok(rules(doc).includes('spelled-out-dates'));

    // And it really would have reached the file: the renderer prints the string it is
    // given, which is why the check has to sit in front of it.
    const text = (await selfTest(await renderResumeDocx(doc), 'docx', doc)).extractedText;
    assert.ok(text.includes('01/2022'), 'the bad date did reach the rendered document');
    assert.ok(containsNumericDate(text));
  });

  await testAsync('the date formatter itself can never emit a numeric date', async () => {
    for (const [start, end] of [
      ['2022-01', '2024-05'],
      ['2022-01', 'present'],
      ['2019', '2021'],
      ['2022-1', '2022-12'],
    ] as const) {
      const rendered = formatDateRange(start, end);
      assert.ok(!containsNumericDate(rendered), `"${rendered}" is locale-ambiguous`);
    }
  });

  // --- decorative bullet ----------------------------------------------------
  await testAsync('catches a decorative bullet character', async () => {
    const doc = goodDoc();
    doc.sections[1].groups![0].items[0].text = '➤ Optimized PostgreSQL queries.';

    assert.ok(rules(doc).includes('plain-bullet-chars'));

    const text = (await selfTest(await renderResumeDocx(doc), 'docx', doc)).extractedText;
    assert.ok(text.includes('➤'), 'the decorative character did reach the rendered document');
  });

  // --- heading not on the allow-list ---------------------------------------
  await testAsync('catches a heading that is not on the allow-list', async () => {
    const doc = goodDoc();
    doc.sections[1].heading = 'My Journey';

    assert.equal(isAllowedHeading('experience', 'My Journey'), false);
    assert.ok(rules(doc).includes('heading-allow-list'));
  });

  await testAsync('the renderer replaces a bad heading rather than printing it', async () => {
    const doc = goodDoc();
    doc.sections[1].heading = 'My Journey';

    assert.equal(coerceHeading('experience', 'My Journey'), 'Experience');

    const text = (await selfTest(await renderResumeDocx(doc), 'docx', doc)).extractedText
      .toLowerCase();
    assert.ok(!text.includes('my journey'), 'the creative heading reached the file');
    assert.ok(text.includes('experience'), 'the canonical heading is missing');
  });

  // --- missing skills section ----------------------------------------------
  await testAsync('catches a document with no skills section', async () => {
    const doc = goodDoc();
    doc.sections = doc.sections.filter((s) => s.key !== 'skills');

    assert.ok(rules(doc).includes('skills-section-required'));

    // The round-trip cannot catch this one: nothing is missing from the file, the file
    // is simply missing a section. Stating that here so the split of responsibility is
    // deliberate rather than an accident nobody noticed.
    const result = await selfTest(await renderResumeDocx(doc), 'docx', doc);
    assert.equal(result.passed, true);
    assert.ok(!(await selfTest(await renderResumeDocx(doc), 'docx', doc)).extractedText
      .toLowerCase()
      .includes('skills'));
  });

  await testAsync('catches a skills section that did not survive rendering', async () => {
    const doc = goodDoc();
    // Deliberately uses skills that DO appear elsewhere in the document. The check used
    // to search the whole extracted text, so this exact case slipped through; it now
    // isolates the Skills region, and a section that vanished is caught either way.
    doc.sections[0].items[0].text = 'React, PostgreSQL, TypeScript';
    const rendered = { ...doc, sections: doc.sections.filter((s) => s.key !== 'skills') };

    // The file was rendered without the skills, but the document claims them — exactly
    // what a template regression that drops a section looks like from the outside.
    const result = await selfTest(await renderResumeDocx(rendered), 'docx', doc);
    assert.equal(result.passed, false);
    const f = failures(result);
    // Two distinct failures now: the heading vanished, or it survived but the skills
    // under it did not. Either is a dropped Skills section from the outside.
    assert.ok(
      f.includes('skills-extractable') || f.includes('skills-section-extractable'),
      `expected a skills failure, got: ${f.join(', ')}`,
    );
  });

  // --- contact info absent --------------------------------------------------
  await testAsync('catches contact details missing from the document model', async () => {
    const doc = goodDoc();
    doc.contact.fullName = '';
    doc.contact.email = '';
    assert.ok(rules(doc).includes('contact-in-body'));
  });

  await testAsync('catches contact details that did not reach the rendered file', async () => {
    const doc = goodDoc();
    const stripped: ResumeDocument = {
      ...doc,
      contact: { ...doc.contact, fullName: 'Someone Else', email: 'nobody@example.com' },
    };

    // Renders a file whose contact block is not the one the document declares — what a
    // resume with its contact details stranded in a header/footer looks like to a parser
    // that skips those regions.
    const result = await selfTest(await renderResumeDocx(stripped), 'docx', doc);
    assert.equal(result.passed, false);
    assert.ok(failures(result).includes('contact-name'));
    assert.ok(failures(result).includes('contact-email'));
  });

  await testAsync('catches a URL that is not readable as plain text', async () => {
    const doc = goodDoc();
    const withoutLinks: ResumeDocument = {
      ...doc,
      contact: { ...doc.contact, portfolioUrl: undefined, githubUrl: undefined },
    };

    const result = await selfTest(await renderResumeDocx(withoutLinks), 'docx', doc);
    assert.equal(result.passed, false);
    assert.ok(failures(result).includes('hyperlink-visible-text'));
  });

  // --- no usable text layer -------------------------------------------------
  await testAsync('catches a file with no usable text layer', async () => {
    const empty: ResumeDocument = {
      ...goodDoc(),
      contact: { fullName: 'A B', email: 'a@b.co' },
      sections: [],
    };

    const result = await selfTest(await renderResumeDocx(empty), 'docx', empty);
    assert.equal(result.passed, false);
    assert.ok(
      failures(result).includes('text-layer'),
      `expected text-layer, got ${JSON.stringify(failures(result))}`,
    );
  });

  // --- presentation mode ----------------------------------------------------
  await testAsync('a presentation-mode document is never scored as an ATS submission', async () => {
    const doc = goodDoc();
    doc.renderMode = 'presentation';
    assert.ok(rules(doc).includes('presentation-mode-not-for-ats'));
  });

  report('render');
})();
