/**
 * ATS round-trip self-test — REQ-6.6.
 *
 * Renders are verified, not trusted. We parse the generated bytes back into plain text
 * exactly the way an ATS would, and assert the things that must survive actually did:
 * name, email, phone, URLs, skills, and section headings — in readable characters, in
 * the right order.
 *
 * This is what catches a template regression (a stray icon, an accidental table, a link
 * that lost its visible URL) BEFORE a broken resume gets sent somewhere that matters.
 */

import mammoth from 'mammoth';
import { ensureDOMMatrix } from './dommatrix';
import type { ResumeDocument } from '../types';

export interface SelfTestIssue {
  severity: 'fail' | 'warn';
  check: string;
  detail: string;
}

export interface SelfTestResult {
  passed: boolean;
  extractedChars: number;
  issues: SelfTestIssue[];
  extractedText: string;
}

/** Private-use area + replacement chars — the icon-font failure signature. */
const GARBLED_PATTERN = /[-�]/;

/**
 * Signatures of "the parser itself couldn't load here", as opposed to "this document
 * is broken". These are bundler/worker resolution failures, which vary by host.
 */
const PARSER_UNAVAILABLE_SIGNATURES = [
  'fake worker',
  'cannot find module',
  'module not found',
  'is not a function',
  'err_package_path_not_exported',
  'err_module_not_found',
  'dynamic require',
  'failed to load',
];

function isParserUnavailable(message: string): boolean {
  const m = message.toLowerCase();
  return PARSER_UNAVAILABLE_SIGNATURES.some((sig) => m.includes(sig));
}

export async function extractTextFromDocx(buffer: Buffer): Promise<string> {
  const { value } = await mammoth.extractRawText({ buffer });
  return value;
}

export async function extractTextFromPdf(buffer: Buffer): Promise<string> {
  // Before the import, not after: pdfjs evaluates `new DOMMatrix()` at module load, and
  // without one — Netlify's Lambda has no native canvas binary — every PDF was refused.
  // See lib/render/dommatrix.ts.
  ensureDOMMatrix();

  // pdf-parse v2 exposes a PDFParse class (v1 exported a bare function). Imported
  // lazily so the pdfjs runtime it pulls in isn't loaded on every request path.
  const { PDFParse } = (await import('pdf-parse')) as unknown as {
    PDFParse: new (opts: { data: Uint8Array }) => {
      getText(): Promise<{ text: string }>;
      destroy?: () => Promise<void>;
    };
  };

  const parser = new PDFParse({ data: new Uint8Array(buffer) });
  try {
    const { text } = await parser.getText();
    return text;
  } finally {
    await parser.destroy?.();
  }
}

export async function selfTest(
  buffer: Buffer,
  format: 'pdf' | 'docx',
  doc: ResumeDocument,
): Promise<SelfTestResult> {
  const issues: SelfTestIssue[] = [];
  let text = '';

  try {
    text =
      format === 'docx'
        ? await extractTextFromDocx(buffer)
        : await extractTextFromPdf(buffer);
  } catch (err) {
    const message = err instanceof Error ? err.message : String(err);

    // Two very different failures wear the same exception, and conflating them would
    // be a bug: a document that genuinely can't be parsed is a broken resume, while a
    // parser that can't even load is an infrastructure problem on this host. The
    // second must not block delivery — the DOCX check validates the same underlying
    // document model, so the shared content is still verified either way.
    if (isParserUnavailable(message)) {
      // Logged, because nothing else records it. The result below is a pass with a
      // warning, the finalize step keeps only failures, and so the host problem behind it
      // reached no one: production reported "0 chars from the PDF" for every draft while
      // the same parser, used by /import, was refusing every PDF a user uploaded.
      console.warn(`[selftest] ${format.toUpperCase()} verifier unavailable on this host:`, message);
      return {
        passed: true,
        extractedChars: 0,
        issues: [
          {
            severity: 'warn',
            check: 'parser-unavailable',
            detail: `The ${format.toUpperCase()} verifier couldn't start on this host (${message.slice(
              0,
              120,
            )}). The file was still generated; verification fell back to the other format.`,
          },
        ],
        extractedText: '',
      };
    }

    return {
      passed: false,
      extractedChars: 0,
      issues: [
        {
          severity: 'fail',
          check: 'extractable',
          detail: `The generated ${format.toUpperCase()} could not be parsed back to text at all: ${message}`,
        },
      ],
      extractedText: '',
    };
  }

  const flat = text.replace(/\s+/g, ' ').trim();
  const lower = flat.toLowerCase();

  // A text-native file always yields substantial text. Near-zero means the page was
  // rasterized or the fonts have no character mapping — invisible to every parser.
  if (flat.length < 200) {
    issues.push({
      severity: 'fail',
      check: 'text-layer',
      detail: `Only ${flat.length} characters extracted — the file has no usable text layer.`,
    });
  }

  if (GARBLED_PATTERN.test(text)) {
    issues.push({
      severity: 'fail',
      check: 'no-garbled-glyphs',
      detail:
        'Private-use-area or replacement characters found — an icon glyph or unmapped font leaked into the document.',
    });
  }

  // --- Contact fields must survive ------------------------------------------
  const c = doc.contact;
  const required: Array<[string, string | undefined]> = [
    ['name', c.fullName],
    ['email', c.email],
  ];
  for (const [label, value] of required) {
    if (!value) continue;
    if (!lower.includes(value.toLowerCase())) {
      issues.push({
        severity: 'fail',
        check: `contact-${label}`,
        detail: `"${value}" did not survive parsing — an ATS would read this resume as missing its ${label}.`,
      });
    }
  }

  for (const [label, value] of [
    ['phone', c.phone],
    ['location', c.location],
  ] as const) {
    if (value && !lower.includes(value.toLowerCase().slice(0, 6))) {
      issues.push({
        severity: 'warn',
        check: `contact-${label}`,
        detail: `"${value}" was not found in the extracted text.`,
      });
    }
  }

  // --- URLs must be readable as text, not only as link metadata --------------
  for (const url of [c.portfolioUrl, c.githubUrl, c.linkedinUrl].filter(Boolean) as string[]) {
    const bare = url.replace(/^https?:\/\//i, '').replace(/\/$/, '').toLowerCase();
    if (!lower.includes(bare)) {
      issues.push({
        severity: 'fail',
        check: 'hyperlink-visible-text',
        detail: `"${bare}" is not present as readable text — if a parser strips link metadata, this address is lost.`,
      });
    }
  }

  // --- Section headings must be found ---------------------------------------
  for (const section of doc.sections) {
    if (!lower.includes(section.heading.toLowerCase())) {
      issues.push({
        severity: 'warn',
        check: 'section-heading',
        detail: `Heading "${section.heading}" not found in extracted text.`,
      });
    }
  }

  // --- Skills must survive, IN the Skills region -----------------------------
  //
  // Searching the whole document was close to useless here: a resume whose Skills
  // section vanished entirely still passed whenever its leading skill happened to
  // appear in a project line, which for a technology-led resume is almost always. The
  // check now isolates the text between the Skills heading and the next heading, which
  // is the zone parsers weight most heavily, and samples several skills rather than
  // trusting one.
  const skills = doc.sections.find((s) => s.key === 'skills');
  const skillsText = skills?.items[0]?.text ?? '';
  if (skillsText) {
    const region = extractSectionRegion(text, skills!.heading, doc);

    if (region === null) {
      issues.push({
        severity: 'fail',
        check: 'skills-section-extractable',
        detail: `The "${skills!.heading}" heading did not survive parsing, so the highest-weighted keyword zone is gone.`,
      });
    } else {
      const wanted = skillsText
        .split(',')
        .map((s) => s.trim().toLowerCase())
        .filter(Boolean)
        .slice(0, 5);
      const regionLower = region.toLowerCase();
      const lost = wanted.filter((w) => !regionLower.includes(w));

      if (lost.length > 0) {
        issues.push({
          severity: 'fail',
          check: 'skills-extractable',
          detail: `${lost.length} of the first ${wanted.length} skills are missing from the extracted Skills section: ${lost.join(', ')}.`,
        });
      }
    }
  }

  return {
    passed: issues.every((i) => i.severity !== 'fail'),
    extractedChars: flat.length,
    issues,
    extractedText: text,
  };
}

/**
 * Text between a section's heading and the next heading in the extracted output.
 *
 * Returns null when the heading itself is missing, which is a distinct and worse
 * failure than the heading being present but empty — the caller reports them
 * separately because they point at different bugs.
 */
function extractSectionRegion(
  text: string,
  heading: string,
  doc: ResumeDocument,
): string | null {
  const haystack = text.toLowerCase();
  const start = haystack.indexOf(heading.toLowerCase());
  if (start === -1) return null;

  const after = start + heading.length;

  // The region ends at whichever other section heading appears first.
  let end = text.length;
  for (const other of doc.sections) {
    if (other.heading === heading) continue;
    const idx = haystack.indexOf(other.heading.toLowerCase(), after);
    if (idx !== -1 && idx < end) end = idx;
  }

  return text.slice(after, end);
}

/**
 * What the self-test actually verified, said plainly.
 *
 * selfTest() above deliberately lets a verifier that cannot start on this host through
 * rather than blocking delivery, because the other format reads the same document
 * model. Reasonable — but the finalize step in lib/pipeline/run.ts then claimed "Both files verified — text extracts
 * cleanly (0 chars from the PDF)" in production: a claim of verification next to a count
 * showing nothing had been read. Zero characters with no failure recorded is precisely
 * the parser-unavailable path; a real read of a broken PDF records a text-layer failure.
 * So it names the file that was checked, and never claims a check that did not run.
 */
export function verifiedMessage(
  pdf: { extractedChars: number; issues: ReadonlyArray<{ check: string }> },
  docx: { extractedChars: number; issues: ReadonlyArray<{ check: string }> },
): string {
  const pdfRan = !pdf.issues.some((i) => i.check === 'parser-unavailable');
  const docxRan = !docx.issues.some((i) => i.check === 'parser-unavailable');
  if (pdfRan && docxRan) {
    return `Both files verified — text extracts cleanly (${pdf.extractedChars} chars from the PDF)`;
  }
  if (docxRan) {
    return `DOCX verified — text extracts cleanly (${docx.extractedChars} chars). The PDF checker can’t run on this server; the PDF is built from the same document.`;
  }
  if (pdfRan) {
    return `PDF verified — text extracts cleanly (${pdf.extractedChars} chars). The DOCX checker can’t run on this server; the DOCX is built from the same document.`;
  }
  return 'Both files were generated, but neither checker can run on this server, so they were not verified.';
}
