/**
 * ATS round-trip self-test — REQ-6.6.
 *
 * Renders are verified, not trusted. We parse the generated bytes back into plain text
 * exactly the way an ATS would, and assert the things that must survive actually did:
 * name, email, phone, URLs, skills, and section headings — in readable characters, in
 * the right order.
 *
 * This is what catches a template regression (a stray icon, an accidental table, a link
 * that lost its visible URL) BEFORE a broken resume gets sent somewhere that matters.
 */

import mammoth from 'mammoth';
import type { ResumeDocument } from '../types';

export interface SelfTestIssue {
  severity: 'fail' | 'warn';
  check: string;
  detail: string;
}

export interface SelfTestResult {
  passed: boolean;
  extractedChars: number;
  issues: SelfTestIssue[];
  extractedText: string;
}

/** Private-use area + replacement chars — the icon-font failure signature. */
const GARBLED_PATTERN = /[-�]/;

/**
 * Signatures of "the parser itself couldn't load here", as opposed to "this document
 * is broken". These are bundler/worker resolution failures, which vary by host.
 */
const PARSER_UNAVAILABLE_SIGNATURES = [
  'fake worker',
  'cannot find module',
  'module not found',
  'is not a function',
  'err_package_path_not_exported',
  'err_module_not_found',
  'dynamic require',
  'failed to load',
];

function isParserUnavailable(message: string): boolean {
  const m = message.toLowerCase();
  return PARSER_UNAVAILABLE_SIGNATURES.some((sig) => m.includes(sig));
}

export async function extractTextFromDocx(buffer: Buffer): Promise<string> {
  const { value } = await mammoth.extractRawText({ buffer });
  return value;
}

export async function extractTextFromPdf(buffer: Buffer): Promise<string> {
  // pdf-parse v2 exposes a PDFParse class (v1 exported a bare function). Imported
  // lazily so the pdfjs runtime it pulls in isn't loaded on every request path.
  const { PDFParse } = (await import('pdf-parse')) as unknown as {
    PDFParse: new (opts: { data: Uint8Array }) => {
      getText(): Promise<{ text: string }>;
      destroy?: () => Promise<void>;
    };
  };

  const parser = new PDFParse({ data: new Uint8Array(buffer) });
  try {
    const { text } = await parser.getText();
    return text;
  } finally {
    await parser.destroy?.();
  }
}

export async function selfTest(
  buffer: Buffer,
  format: 'pdf' | 'docx',
  doc: ResumeDocument,
): Promise<SelfTestResult> {
  const issues: SelfTestIssue[] = [];
  let text = '';

  try {
    text =
      format === 'docx'
        ? await extractTextFromDocx(buffer)
        : await extractTextFromPdf(buffer);
  } catch (err) {
    const message = err instanceof Error ? err.message : String(err);

    // Two very different failures wear the same exception, and conflating them would
    // be a bug: a document that genuinely can't be parsed is a broken resume, while a
    // parser that can't even load is an infrastructure problem on this host. The
    // second must not block delivery — the DOCX check validates the same underlying
    // document model, so the shared content is still verified either way.
    if (isParserUnavailable(message)) {
      return {
        passed: true,
        extractedChars: 0,
        issues: [
          {
            severity: 'warn',
            check: 'parser-unavailable',
            detail: `The ${format.toUpperCase()} verifier couldn't start on this host (${message.slice(
              0,
              120,
            )}). The file was still generated; verification fell back to the other format.`,
          },
        ],
        extractedText: '',
      };
    }

    return {
      passed: false,
      extractedChars: 0,
      issues: [
        {
          severity: 'fail',
          check: 'extractable',
          detail: `The generated ${format.toUpperCase()} could not be parsed back to text at all: ${message}`,
        },
      ],
      extractedText: '',
    };
  }

  const flat = text.replace(/\s+/g, ' ').trim();
  const lower = flat.toLowerCase();

  // A text-native file always yields substantial text. Near-zero means the page was
  // rasterized or the fonts have no character mapping — invisible to every parser.
  if (flat.length < 200) {
    issues.push({
      severity: 'fail',
      check: 'text-layer',
      detail: `Only ${flat.length} characters extracted — the file has no usable text layer.`,
    });
  }

  if (GARBLED_PATTERN.test(text)) {
    issues.push({
      severity: 'fail',
      check: 'no-garbled-glyphs',
      detail:
        'Private-use-area or replacement characters found — an icon glyph or unmapped font leaked into the document.',
    });
  }

  // --- Contact fields must survive ------------------------------------------
  const c = doc.contact;
  const required: Array<[string, string | undefined]> = [
    ['name', c.fullName],
    ['email', c.email],
  ];
  for (const [label, value] of required) {
    if (!value) continue;
    if (!lower.includes(value.toLowerCase())) {
      issues.push({
        severity: 'fail',
        check: `contact-${label}`,
        detail: `"${value}" did not survive parsing — an ATS would read this resume as missing its ${label}.`,
      });
    }
  }

  for (const [label, value] of [
    ['phone', c.phone],
    ['location', c.location],
  ] as const) {
    if (value && !lower.includes(value.toLowerCase().slice(0, 6))) {
      issues.push({
        severity: 'warn',
        check: `contact-${label}`,
        detail: `"${value}" was not found in the extracted text.`,
      });
    }
  }

  // --- URLs must be readable as text, not only as link metadata --------------
  for (const url of [c.portfolioUrl, c.githubUrl, c.linkedinUrl].filter(Boolean) as string[]) {
    const bare = url.replace(/^https?:\/\//i, '').replace(/\/$/, '').toLowerCase();
    if (!lower.includes(bare)) {
      issues.push({
        severity: 'fail',
        check: 'hyperlink-visible-text',
        detail: `"${bare}" is not present as readable text — if a parser strips link metadata, this address is lost.`,
      });
    }
  }

  // --- Section headings must be found ---------------------------------------
  for (const section of doc.sections) {
    if (!lower.includes(section.heading.toLowerCase())) {
      issues.push({
        severity: 'warn',
        check: 'section-heading',
        detail: `Heading "${section.heading}" not found in extracted text.`,
      });
    }
  }

  // --- Skills must survive: the highest-weighted zone for parsers ------------
  const skills = doc.sections.find((s) => s.key === 'skills');
  if (skills?.items[0]?.text) {
    const first = skills.items[0].text.split(',')[0]?.trim().toLowerCase();
    if (first && !lower.includes(first)) {
      issues.push({
        severity: 'fail',
        check: 'skills-extractable',
        detail: `The Skills section did not survive parsing (looked for "${first}").`,
      });
    }
  }

  return {
    passed: issues.every((i) => i.severity !== 'fail'),
    extractedChars: flat.length,
    issues,
    extractedText: text,
  };
}
