/**
 * Regenerates lib/render/fonts/data.ts from the TTFs beside it.
 *
 * WHY THE FONTS ARE A TS MODULE AND NOT FILES READ AT RUN TIME
 *
 * The PDF renderer runs in a serverless function. Reading `lib/render/fonts/*.ttf` with
 * `fs` from `process.cwd()` only works if build-time file tracing copies those files into
 * the function bundle, and tracing cannot see a path that is built at run time — the same
 * class of failure as pdfjs's worker file (see scripts/verify-pdf-without-canvas.mts),
 * which was absent in production while every local run passed. A base64 string in a module
 * is bundled by definition: if the module is imported, the bytes are there. @react-pdf
 * accepts a `data:` URL as a font source, so nothing else is needed.
 *
 * The cost is ~2.6 MB of source for ~1.9 MB of fonts, paid only by the server bundle that
 * renders PDFs.
 *
 * Run: npx tsx --tsconfig scripts/tsconfig.json scripts/build-font-data.mts
 */

import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const dir = join(dirname(fileURLToPath(import.meta.url)), '..', 'lib', 'render', 'fonts');

export const FONT_FILES = [
  'NotoSans-Regular',
  'NotoSans-Bold',
  'NotoSansDevanagari-Regular',
  'NotoSansDevanagari-Bold',
  'NotoSansTamil-Regular',
  'NotoSansTamil-Bold',
] as const;

const lines = [
  '/**',
  ' * GENERATED by scripts/build-font-data.mts from the TTFs in this directory. Do not edit.',
  ' * Noto Sans, Noto Sans Devanagari and Noto Sans Tamil, SIL Open Font License 1.1 — see',
  ' * the OFL-*.txt files beside the TTFs. Why this is a module: the script header.',
  ' */',
  '',
  'export const FONT_DATA: Record<string, string> = {',
];
for (const name of FONT_FILES) {
  const b64 = readFileSync(join(dir, `${name}.ttf`)).toString('base64');
  lines.push(`  '${name}': '${b64}',`);
}
lines.push('};', '');
writeFileSync(join(dir, 'data.ts'), lines.join('\n'));
console.log('wrote lib/render/fonts/data.ts');
